# -*- coding: utf-8 -*-
"""route_matrix.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-5HkFeeoA6PreX1idFH-Hg1RngZ7N1mI
"""

import requests
from json import loads
link = "https://atlas.microsoft.com/route/matrix/json?subscription-key=8Gc_brD9CgHHB6zUEea-qDdBREj_1Vs7BWztozsSjho&api-version=1.0&routeType=shortest"
data = {
  "origins": {
    "type": "MultiPoint",
    "coordinates": [[19.155001,72.849998],
                    [24.7945,73.055],
                    [26.85,80.949997],
                    [19.07609,72.877426],
                    [14.16704,75.040298],
                    [26.540457,88.719391]]
  },
  "destinations": {
    "type": "MultiPoint",
    "coordinates": [[19.155001,72.849998],
                    [24.7945,73.055],
                    [26.85,80.949997],
                    [19.07609,72.877426],
                    [14.16704,75.040298],
                    [26.540457,88.719391]]
  }
}
def get_distance_matrix(data):
  r = requests.post(link,json=data)
  if r.status_code == 202:
    result = requests.get(r.headers['Location'])
    matrix = loads(result.text)
    print(matrix)
    for i in range(6):
      for j in range(6):
        print(matrix['matrix'][i][j]['response']['routeSummary']['lengthInMeters'])
      print("\n")
    return matrix
  else:
    raise ValueError(r.content)

get_distance_matrix(data)
