# -*- coding: utf-8 -*-
"""route_matrix.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-5HkFeeoA6PreX1idFH-Hg1RngZ7N1mI
"""

import requests
from json import loads
import copy

link = "https://atlas.microsoft.com/route/matrix/json?subscription-key=8Gc_brD9CgHHB6zUEea-qDdBREj_1Vs7BWztozsSjho&api-version=1.0&routeType=shortest"

def get_distance_matrix(location_data):
  len = 17
  r = requests.post(link,json=location_data)
  if r.status_code == 202:
    result = requests.get(r.headers['Location'])
    matrix = loads(result.text)
    #print(matrix)
    DistanceMatrix= []
    for i in range(len):
      temp = []
      for j in range(len):
        temp.append(matrix['matrix'][i][j]['response']['routeSummary']['lengthInMeters']*0.001)
      DistanceMatrix.append(copy.copy(temp))
    return DistanceMatrix
  else:
    raise ValueError(r.content)





